### ISSUE TITLE
Add a clang-format configuration file

### ISSUE THREAD

**Issue by program--** [NOAA-OWP/ngen#614]
Add a `.clang-format` file for use with [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to ensure consistent code styling based on [NGen documentation](https://noaa-owp.github.io/ngen/md_doc_programming_standards.html).

Example configuration that we could potentially use:

```yaml
---
BasedOnStyle: Google
AlignAfterOpenBracket: AlwaysBreak
AlignConsecutiveMacros: 'true'
AlignEscapedNewlines: Left
Cpp11BracedListStyle: 'true'
DerivePointerAlignment: 'true'
FixNamespaceComments: 'true'
IncludeBlocks: Regroup
IndentCaseLabels: 'true'
IndentPPDirectives: AfterHash
IndentWidth: '4'
Language: Cpp
NamespaceIndentation: None
SortIncludes: 'true'
SortUsingDeclarations: 'true'
SpaceAfterTemplateKeyword: 'false'
SpaceBeforeAssignmentOperators: 'true'
SpaceBeforeCtorInitializerColon: 'true'
SpaceBeforeInheritanceColon: 'true'
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: 'true'
SpaceInEmptyParentheses: 'false'
SpacesInAngles: 'false'
SpacesInContainerLiterals: 'false'
SpacesInParentheses: 'false'
SpacesInSquareBrackets: 'false'
Standard: Cpp11
UseTab: Never
```

Another example: [My personal .clang-format](https://gist.github.com/program--/0e1a8d594994b1c6d9d9e3105ef814c6).
